### ISSUE TITLE
Off-by-one error when reading input file as binary

### ISSUE THREAD

**Issue by ORichterSec** [dj-on-github/djent#2]
When reading a file with the `-b` flag the program says the number of symbols is one less than it should be.
#### Example:
lets create a file with dd of size 100 bytes:
`dd if=/dev/random of=out.bin count=100 bs=1`
Then we feed it into djent with the `-b` flag:
`djent out.bin -b -l 8`

#### Expected Output:
...
`Analysing 100 8-bit symbols`
...

#### Actual Output:
...
`Analysing 99 8-bit symbols`
...

Also the printed output does not work correctly if we omit the `-l 8`. (i.e. `djent out.bin -b`)
#### Expected Output:
`Analysing 800 1-bit symbols`

#### Actual Output:
`Analysing 792 1-bit symbols`

Seems to me like the that the error may have to do with lines 2004 ff. , where there is a try to fix a off-by-one. But it seems not to work correctly (at least with the `-b` flag)

**Comment by dj-on-github** [comment]
Yep. You're right. It's the same for me. 
Time to fettle the code.

**Comment by dj-on-github** [comment]
I tried a few cases with and without '-b' and it was consistently off by 1. So I removed the post increment and it seems to work. Let me know if this works for you.

**Comment by ORichterSec** [comment]
Well for the case, when i run with the flags `-b -l 8` so:
`./djent out.bin -b -l 8`
,then the output is as i would have expected `Analysing 100 8-bit symbols`.
If i analyze the same file without the `-l 8` i. e. :
`./djent out.bin -b`
, then the output is still wrong i think: `Analysing 793 1-bit symbols`.
I think i should also say `Analysing 800 1-bit symbols`.

**Comment by dj-on-github** [comment]
I'm closing this. I think it's fixed. If you find a combination that doesn't work, feel free to rant that I didn't fix it and tell me I'm a bad programmer.
